name: Server Deploy

on:
  push:
    branches: [main]
    paths:
      - 'src/**'

jobs:
  server:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradlew
        run: ./gradlew build

      - name: Docker build
        run: |
          docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
          docker build -t spring-cicd .
          docker tag spring-cicd ${{secrets.DOCKER_HUB_USERNAME}}/spring-cicd:${GITHUB_SHA::7}
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/spring-cicd:${GITHUB_SHA::7}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Deploy to Server
        run: |
          aws ssm send-command \
            --instance-id i-04fccea6f0f7c7810 \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[
              'if sudo docker ps -a --format \\'{{.Names}}\\' | grep -q \'^server$\\'; then',
              '  sudo docker stop server',
              '  sudo docker rm server',
              'fi',
              'sudo docker pull ${{secrets.DOCKER_HUB_USERNAME}}/spring-cicd:${GITHUB_SHA::7}',
              'sudo docker run -d --name server -p 8080:8080 \
                -e AWS_ACCESS_KEY=${{secrets.AWS_ACCESS_KEY}} \
                -e AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} \
                -e DOCKER_HUB_PASSWORD=${{secrets.DOCKER_HUB_PASSWORD}} \
                -e DOCKER_HUB_USERNAME=${{secrets.DOCKER_HUB_USERNAME}} \
                ${{secrets.DOCKER_HUB_USERNAME}}/spring-cicd:${GITHUB_SHA::7}'
            ]"
